services:
  nginx:
    image: nginx:alpine
    container_name: nginx-app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx/development.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

  php:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: php-app
    volumes:
      - .:/var/www/html
      - './php/php.ini:/usr/local/etc/php/php.ini'
    depends_on:
      - mysql
      - nginx
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    restart: unless-stopped
    container_name: mysql-app
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
